name: Unit Tests

on:
  workflow_call:
  push:
    branches: [main]
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, converted_to_draft]

concurrency:
  group: unit-tests_${{ github.workflow }}_${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Nuxt Prepare
        run: npm exec nuxt prepare

      - name: Run tests
        if: github.event_name == 'workflow_dispatch'
        run: npm run test

      - name: Run tests coverage
        if: github.event_name != 'workflow_dispatch'
        run: npm run coverage

      - name: Upload coverage reports to Codecov
        if: github.event_name != 'workflow_dispatch'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
